permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "Yuqin Wang"
email: w17600296313@gmail.com
description: "你赤手空拳来到人间，为找到那片海不顾一切。"
github:
  username: yukia-yuqin
  
url: "https://yukia-yuqin.github.io/blog"
imgrepo: "https://bit-ranger.github.io/blog/static/img"

gitment:
  enable:true
  githubID:yukia-yuqin
  repo:blog.github.io
  ClientID:7d1a455a0adbb5a545f0
  ClientSecret:4bc0585ad123c1851b66a27e7b758103227ff2ba
  lazy:false

#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

